server:
  port: 8080

spring:
  application:
    name: spring-security-template
  profiles:
    active: prod
api:
  security:
    token:
      secret: ${JWT_SECRET:secret}
      issuer: ${JWT_ISSUER:issuer}